### ISSUE TITLE
Add swift type search

### ISSUE THREAD

**Issue by cammace** [mapbox/android-docs#10]

**Comment by zugaldia** [comment]
@cammace What do you mean with this?

**Comment by cammace** [comment]
We use swift type for documentation searching on our [help page](https://www.mapbox.com/help/). It would be nice to bring this same functionality to the sdk docs. The first step would be working it into the documentation design.

**Comment by langsmith** [comment]
Closing as this is a higher level docs decision made by @mapbox/docs . https://docs.mapbox.com/help/  just received a search bar. A bar like it would be added to all docs pages rather than just the android docs.

**Comment by colleenmcginnis** [comment]
Yes! Coming soon to a repo near you. 💁 cc @katydecorah
