### ISSUE TITLE
Fix NonNull and AppCompatActivity import lines for maps, java, and plugins examples

### ISSUE THREAD

**Issue by langsmith** [mapbox/android-docs#1006]
These import lines
```
android.support.annotation.NonNull;
android.support.v7.app.AppCompatActivity
```
need to change to
```
import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
```

for _all_ examples at https://docs.mapbox.com/android/maps/examples/, https://docs.mapbox.com/android/plugins/examples/, and https://docs.mapbox.com/android/java/examples/

For some reason, this wasn't picked up by https://github.com/mapbox/android-docs/blob/publisher-production/CONTRIBUTING.md#run-the-add-examples-script.  https://github.com/mapbox/mapbox-android-demo/pull/1104 is the pr where AndroidX was introduced.

**Comment by langsmith** [comment]
There seems to be something out of sync. For example, https://docs.mapbox.com/android/maps/examples/slowly-rotating-camera/ shows 

```
import android.support.annotation.NonNull;
import android.support.v7.app.AppCompatActivity;
```

but the `SlowlyRotatingCameraActivity.java` file in this repo has 

```
import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
```

![Screen Shot 2019-07-22 at 1 25 11 PM](https://user-images.githubusercontent.com/4394910/61662868-2cdf4100-ac84-11e9-8874-d1c6462ee1eb.png)


@colleenmcginnis , do you understand what's going on with this mismatch?

**Comment by colleenmcginnis** [comment]
@langsmith I'm not sure I understand the issue here... I'm seeing `androidx` on the live site. Is that what you expect to see? 

![image](https://user-images.githubusercontent.com/10479155/61665881-04a71080-ac8b-11e9-813f-c8902794e987.png)

**Comment by langsmith** [comment]
https://github.com/mapbox/android-docs/commit/02926f2f58e8d00c4d6c54daf9ef5303ca45031e resolves this
