### ISSUE TITLE
Missing MAS v2.1.1 API reference

### ISSUE THREAD

**Issue by 1ec5** [mapbox/android-docs#101]
[Mapbox Android Services v2.1.1](https://github.com/mapbox/mapbox-java/releases/tag/v2.1.1) has been released, but the API reference doesn’t seem to have been uploaded yet.

/ref #61
/cc @langsmith @cammace

**Comment by cammace** [comment]
The links just haven't been updated, the API documentation currently gets pushed directly to `mb-pages` instead of into master (limitation of Gatsby), https://github.com/mapbox/android-docs/tree/mb-pages/api/mapbox-java

**Comment by 1ec5** [comment]
Ah, I think I got confused by the URL structure when trying it out earlier (“android-docs” versus “mapbox-java”). Closing in favor of #102.
