### ISSUE TITLE
Feedback for /android/maps/examples/query-a-map-feature/

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/android-docs#1010]
*Feedback:*

* Page: [/android/maps/examples/query-a-map-feature/](https://docs.mapbox.com/android/maps/examples/query-a-map-feature/)
* Section: maps
* Was this page helpful?: 😕

Feedback:
> marker options are deprecated, how do I use by symbollayer or markerview

**Comment by langsmith** [comment]
Agree. Refactoring is needed. `/mapbox-android-demo` ticket created at https://github.com/mapbox/mapbox-android-demo/issues/1144 for tracking.

**Comment by HeyStenson** [comment]
Thanks @langsmith!

**Comment by langsmith** [comment]
https://github.com/mapbox/mapbox-android-demo/pull/1148 landed and https://docs.mapbox.com/android/maps/examples/query-a-map-feature was eventually updated downstream.
