### ISSUE TITLE
Feedback for /android/plugins/overview/annotation/

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/android-docs#1015]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/android/plugins/overview/annotation/](https://docs.mapbox.com/android/plugins/overview/annotation/)
* Section: plugins
* Date received: 2019-07-23T08:11:57.462Z
* Was this page helpful?: 😕

Feedback:
> I do this and it isn't showing anything // set non data driven properties symbolManager.setIconAllowOverlap(true); symbolManager.setTextAllowOverlap(true); // create a symbol SymbolOptions symbolOptions = new SymbolOptions() .withLatLng(new LatLng(6.687337, 0.381457)) .withIconImage(ID_ICON_AIRPORT) .withIconSize(1.3f) .withSymbolSortKey(10.0f) .withDraggable(true); symbol = symbolManager.create(symbolOptions); Timber.e(symbol.toString());

This looks like it may be outside the scope of the example here https://docs.mapbox.com/android/plugins/overview/annotation/#manager, but wanted to flag just in case that example does need to be reevaluated. Feel free to close this issue if it's not relevant!

**Comment by langsmith** [comment]
Thanks. We're good here. I'm suprised that people don't use the feedback box more for Zendesk support type of questions/grievances 😛
