### ISSUE TITLE
Feedback for /android/maps/examples/support-map-fragment/

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/android-docs#1016]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/android/maps/examples/support-map-fragment/](https://docs.mapbox.com/android/maps/examples/support-map-fragment/)
* Section: maps
* Date received: 2019-07-23T14:36:18.088Z
* Was this page helpful?: 😕

Feedback:
> What is the detail of the "R.layout.activity_basic_support_map_frag" file?

We could consider adding an in-line comment here about what `R.layout.activity_basic_support_map_frag` refers to?

**Comment by langsmith** [comment]
The person wants to see the specifics of the `R.layout.activity_basic_support_map_frag` file 👇 

<br>

![Screen Shot 2019-07-24 at 10 59 39 AM](https://user-images.githubusercontent.com/4394910/61816913-2bd41e00-ae02-11e9-91eb-fee6dab23e54.png)

The example pages, such as https://docs.mapbox.com/android/maps/examples/support-map-fragment/, are automatically generated. 

Once @colleenmcginnis ' https://github.com/mapbox/android-docs/pull/950 lands, it'll be easier for folks to make the connection between the examples and the github version. Once they're in Github, they can explore to find the specific `R.layout` file for the demo app example that they're interested in.

**Comment by HeyStenson** [comment]
Thanks @langsmith! 🚀
