### ISSUE TITLE
Examples: add links to source java and layout files

### ISSUE THREAD

**Issue by danswick** [mapbox/android-docs#1032]
This topic has come up a few times [in the past](https://github.com/mapbox/android-docs/issues/1016) and continues to show up in user feedback, so this ticket is here to centralize and track it. 

## Why?

Because our examples only show the relevant activity's java file, it can be confusing for users who want to replicate the example, but aren't sure how to set up their corresponding layout file. Users may have landed on the example page from elsewhere and aren't aware that there's a full open source project for them to peruse. 

## How? 

@colleenmcginnis started this work [here](https://github.com/mapbox/android-docs/pull/950), but it looks like it hit a speedbump. We should determine if this is still the direction we want to go and whether we'd be able to link to the relevant layout file as well.

**Comment by langsmith** [comment]
https://github.com/mapbox/android-docs/pull/950 should be completed. Once it is completed, it'll be enough. We need to go through the work of adding an XML layout link as well. Once a reader is linked to the actual Github `Activity` file, the reader can explore Github and find the correct layout file or other files.

**Comment by colleenmcginnis** [comment]
Done in https://github.com/mapbox/android-docs/pull/1041 💁
