### ISSUE TITLE
Feedback for /android/maps/examples/add-a-wms-source/ (maps)

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/android-docs#1034]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/android/maps/examples/add-a-wms-source/](https://docs.mapbox.com/android/maps/examples/add-a-wms-source/)
* Section: maps
* Date received: 2019-08-09T20:12:58.928Z
* Was this page helpful?: 😕

Feedback:
> Can't connect to the example link for the WMS

The link to https://geodata.state.nj.us/ does indeed seem to be dead. Might be temporary, or we might need to find a new imagery source here.

**Comment by langsmith** [comment]
Yes, this demo app 🐛 is being tracked at https://github.com/mapbox/mapbox-android-demo/issues/1020

**Comment by HeyStenson** [comment]
Thanks @langsmith! Since this is already being tracked in mapbox/mapbox-android-demo#1020, I'll close this issue.
