### ISSUE TITLE
Feedback for /android/maps/examples/floor-plan/ (maps)

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/android-docs#1038]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/android/maps/examples/floor-plan/](https://docs.mapbox.com/android/maps/examples/floor-plan/)
* Section: maps
* Date received: 2019-08-12T07:04:01.784Z
* Was this page helpful?: 😕

Feedback:
> can not find Indoor geoJson data

Is it possible for us to provide a sample GeoJSON asset (like the `white_house_lvl_0.geojson` file referenced in the example) so that users can recreate this example?

**Comment by langsmith** [comment]
> can not find Indoor geoJson data

https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/assets/white_house_lvl_0.geojson & https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/assets/white_house_lvl_1.geojson

We shouldn't go about customizing various https://docs.mapbox.com/android/maps/examples pages with different files (e.g. XML layout files on some pages, GeoJSON files on others, etc). 

Once https://github.com/mapbox/android-docs/pull/950 lands, folks can explore Github and find what they need.

**Comment by HeyStenson** [comment]
Perf, thanks @langsmith!
