### ISSUE TITLE
Replace remaining @mapbox/react-* with @mapbox/mr-ui/*

### ISSUE THREAD

**Issue by colleenmcginnis** [mapbox/android-docs#1048]
We have a few lingering references to older versions of shared components. I'll do a full sweep for these and update to `@mapbox/mr-ui`. 

Note: I think there might be one older reference that we wanted to keep -- I'll investigate before getting started. 

cc @katydecorah

**Comment by katydecorah** [comment]
closing in favor of #859 :)

**Comment by colleenmcginnis** [comment]
🙈
