### ISSUE TITLE
how to style the layer using expression - get more than one property

### ISSUE THREAD

**Issue by bar3200** [mapbox/android-docs#1075]
I have circle layer and I want to match color based on two properties.

Is there any expression to do that?

**Comment by langsmith** [comment]
Hi @bar3200 , thanks for using Mapbox. This repo is for issues with Android documentation, rather than Mapbox implementation questions. Please contact the Mapbox Support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 to get the help that you need.
