### ISSUE TITLE
Adding Swiftype meta tags to API Reference

### ISSUE THREAD

**Issue by langsmith** [mapbox/android-docs#110]
_This ticket was originally an issue in the (now deprecated) Android SDK repo and has been moved to this repo. Originally created by_ @katydecorah 

Right now the [Maps SDK for Android API Reference](https://www.mapbox.com/android-sdk/api/5.0.2/) does not provide useful metadata to Swiftype to help guide our search results. For example:

![image](https://cloud.githubusercontent.com/assets/2180540/26594469/b5dd07ac-4535-11e7-8aa4-addbff8113c2.png)

We should add Swiftype meta tags to improve our search results. This is especially important for the help redesign (cc mayagao).

Here's what we need (with example data from Mapbox.js):

```html
<!-- name of the subsite (remains constant) -->
<meta class='swiftype' name='type' data-type='enum' content='Mapbox.js' /> 
<!-- version number of the API -->
<meta class='swiftype' name='info' data-type='string' content='v3.1.1' /> 
<!-- title of current page -->
<meta class='swiftype' name='title' data-type='string' content='v3.1.1 JavaScript Library: All' /> 
<!-- excerpt/description of the current page, set manually or the first 30 words of the page's content -->
<meta class='swiftype' name='excerpt' data-type='string' content='Build anything with Mapbox.js v3.1.1, a library for fast &amp; interactive maps.' /> 
<!-- prevent older versions of the API from being crawled -->
<!-- NEEDS LOGIC: if page version !== latest version, print: <meta name='robots' content='noindex'> -->
```

With better meta tags, we should be able to filter out previous versions of the SDK which is why there are duplicates right now.

From experience of seeking to add these tags to a few other generated docs, I found that it's not always easy to get the data for the meta tags I proposed above. That said, if we could have at least these following tags, then we'd be in good shape:

```html
<!-- name of the subsite (remains constant) -->
<meta class='swiftype' name='type' data-type='enum' content='Mapbox.js' /> 
<!-- title of current page -->
<meta class='swiftype' name='title' data-type='string' content='v3.1.1 JavaScript Library: All' /> 
```
---

@cammace 

Similar mission as https://github.com/mapbox/ios-sdk/pull/296

**Comment by langsmith** [comment]
I'm not sure what the current status of Swiftype is for mobile usage. Can this be closed @katydecorah ?

**Comment by katydecorah** [comment]
@langsmith looks like Swiftype tags were added to the docs. We're good here!
