### ISSUE TITLE
Fix the directions example 

### ISSUE THREAD

**Issue by langsmith** [mapbox/android-docs#111]
_This ticket was originally an issue in the (now deprecated) Android SDK repo and has been moved to this repo. Originally created by_ @cammace 

reported by user:

```
Isnt there a chance of a memory leak resulting from the example code listed on https://www.mapbox.com/android-sdk/examples/directions/? 

What happens someone rotates the device before the network call finishes? 
Shouldn't MapboxDirections client be declared as activity-wide var, and then onDestroy(if called) should check to see if that is null, and if not, should call client.cancelCall() ? Thats the general pattern I handle most of my calls(with retrofit).
```
This has been fixed in the demo app along with map matching example. Still needs to be updated in documentation...

**Comment by cammace** [comment]
> This has been fixed in the demo app

since the examples point to the demo app I think we are safe to close this. If I'm wrong, please reopen @langsmith
