### ISSUE TITLE
Better marker view example

### ISSUE THREAD

**Issue by langsmith** [mapbox/android-docs#112]
_This ticket was originally an issue in the (now deprecated) Android SDK repo and has been moved to this repo. Originally created by_ @incanus 

In our [marker view example](https://github.com/mapbox/android-sdk/blob/bd893399a84190e440c4cf2b8b86106535bee92b/_posts/examples/0200-01-15-marker-view.html), we pretty much replicate the [custom marker icon](https://github.com/mapbox/android-sdk/blob/bd893399a84190e440c4cf2b8b86106535bee92b/_posts/examples/0200-01-06-custom-marker-icon.html) example, since we provide an `Icon` and just have a few new knobs to tweak such as `rotation`, `anchor`, and `alpha`. 

``` java
IconFactory iconFactory = IconFactory.getInstance(MainActivity.this);
Drawable iconDrawable = ContextCompat.getDrawable(MainActivity.this, R.drawable.purple_marker);
Icon icon = iconFactory.fromDrawable(iconDrawable);

// Add a marker view using all of the options available
mapboxMap.addMarker(new MarkerViewOptions()
        .position(new LatLng(-37.822829, 144.981842))
        .icon(icon)
        .rotation(90)
        .anchor(0.5f, 0.5f)
        .alpha(0.5f)
        .title("Hisense Arena")
        .snippet("Olympic Blvd, Melbourne VIC 3001, Australia")
        .infoWindowAnchor(0.5f, 0.5f)
        .flat(true));
```

That is, it's not super clear why an API such as marker views exists since we could do rotation and such in core GL (if we chose to expose them). 

Compare to our in-SDK test app scalable marker example, which Java-side scales a marker view in response to an in-app slider. This is the sort of thing that clarifies why you'd ever want Java-side views on the map and would make a better example. Maybe not this exactly, but something like this that manipulates a view after it has been attached to the map as a marker. 

**Also**: https://github.com/mapbox/mapbox-android-demo/issues/115#issuecomment-237031271

**Comment by cammace** [comment]
Closing this ticket since we have no need to push marker views onto users when symbol layers are available now and allow for most of this functionality. Also, Marker views will be moved into a plugin in the future.
