### ISSUE TITLE
how to opt out from telemetry programmatically when hiding the attribution control?

### ISSUE THREAD

**Issue by katydecorah** [mapbox/android-docs#1132]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/android/maps/overview/](https://docs.mapbox.com/android/maps/overview/)
* Section: maps
* Date received: 2019-10-22T14:20:13.642Z
* Was this page helpful?: 😕

Feedback:
> There are no instructions on how to opt out from telemetry programmatically when hiding the attribution control.

---

@langsmith do you know of an example or another source we can link to in this paragraph?

> ![image](https://user-images.githubusercontent.com/2180540/67496977-40b38e00-f64b-11e9-9704-0247fa6804fa.png)

**Comment by langsmith** [comment]
I'm closing because I think disabling telem isn't something we want code snippets for
