### ISSUE TITLE
Add complete example for SymbolManager

### ISSUE THREAD

**Issue by danswick** [mapbox/android-docs#1133]
*This feedback was submitted by a user through the feedback widget on the bottom of the page.*

* Page: [/android/plugins/overview/annotation/](https://docs.mapbox.com/android/plugins/overview/annotation/)
* Section: plugins
* Date received: 2019-10-28T13:34:18.995Z
* Was this page helpful?: 😕

Feedback:
> I cant find information on how to add markers with the SymbolManager

**Comment by langsmith** [comment]
Will be resolved by https://github.com/mapbox/android-docs/pull/1154
