### ISSUE TITLE
Example for SharedPreferences

### ISSUE THREAD

**Issue by tsuz** [mapbox/android-docs#1137]
Hi,

In this [Shared Preferences](https://docs.mapbox.com/android/maps/examples/shared-preferences/), I think the title **Shared Preferences** is a little misleading because this example is showing that the app can save the location to *SharedPreferences* and retrieve from it. Maybe we could change the title to **Saving to SharedPreferences** which makes it clearer to the developer that this is about saving to local storage.

@mapbox/android

Thanks,

Taku

**Comment by langsmith** [comment]
Thanks @tsuz . The title comes from https://github.com/mapbox/mapbox-android-demo. I've opened https://github.com/mapbox/mapbox-android-demo/pull/1256, which will resolve this issue once it's merged to `master` and then when I go through the example sync update process here in this repo 👍  

Please ✅ https://github.com/mapbox/mapbox-android-demo/pull/1256 when you get a chance.

**Comment by tsuz** [comment]
Hi @langsmith the PR looks good! Thanks 👍

**Comment by zugaldia** [comment]
With https://github.com/mapbox/mapbox-android-demo/pull/1256 merged, are we good to close here?

**Comment by langsmith** [comment]
Yep, we're good to close.
