### ISSUE TITLE
easeCamera description

### ISSUE THREAD

**Issue by tsuz** [mapbox/android-docs#1138]
Hi,

In the [docs](https://docs.mapbox.com/android/maps/overview/camera/), there is a description of `easeCamera` that says

>  If you plan to have the map camera track the current user as they move this is the correct API to use since one of the parameters can be set to false, Disabling the animation interpolator and resulting in a linear ease animation.

Other than grammatical mistakes, I am not sure what "one of the parameters can be set to false" means. Can we clarify this portion?

CC: @mapbox/android

Thanks,

Taku

**Comment by zugaldia** [comment]
These are the different signatures for the `easeCamera()` method:

![image](https://user-images.githubusercontent.com/6964/68618725-faa65900-0497-11ea-9e08-80fc8f77c53f.png)

I believe that what the documentation above recommends is setting `easingInterpolator` to `false` in the versions that support that parameter (e.g. `easeCamera(CameraUpdate update, int durationMs, boolean easingInterpolator)`).

@langsmith could you take a pass at clarifying the text in the OP?

**Comment by langsmith** [comment]
Sure, will do

**Comment by langsmith** [comment]
Fix for this is moving at https://github.com/mapbox/android-docs/pull/1153
