### ISSUE TITLE
"Directions API does not return ETA"

### ISSUE THREAD

**Issue by tsuz** [mapbox/android-docs#1139]
Hi,

In this [docs](https://docs.mapbox.com/android/java/overview/directions/), there is a sentence that says

> The Directions API does not return estimated times of arrival (ETA).

However, in the curl example, 

```
# curl "https://api.mapbox.com/directions/v5/mapbox/cycling/-122.42,37.78;-77.03,38.91?access_token=pk.eyJ1IjoidGFrdXRvc3V6dWtpbWFwYm94IiwiYSI6ImNrMjJlMXplcTE4a2czY3F3MWkxZHN4cWkifQ.CRcFM34KAOiPKIbscodOqA" | json_pp

{
   ...
   "routes" : [
      {
         "duration" : 1382416,
         ...
      }
   ]
}

```

I believe `response.routes.reduce((p, c) => c.duration + p, 0)` should return total duration and thus ETA can be calculated. 

So, I'm confused by the statement in the docs. Is it saying that it will not return "eta" (or alias of it) parameter or "duration" cannot be calculated from the response? 

@mapbox/android 

Thanks in advance,

Taku

**Comment by langsmith** [comment]
Thanks @tsuz . I think that what happened is that the page was written when `duration` wasn't part of the API response and then the page was never updated.

I've opened #1152 to fix this.
