### ISSUE TITLE
Create "extrusions" sidebar for Maps SDK for Android overview page

### ISSUE THREAD

**Issue by ZiZasaurus** [mapbox/android-docs#1170]
I have a customer who struggled with implementing extrusions within his app (similar concept to our [Use GeoJSON data to set extrusion height](https://docs.mapbox.com/android/maps/examples/use-geojson-data-to-set-extrusion-height/) example) and is requesting documentation be made available to help customers who may run into similar issues. 

It would be great if we could have a sidebar within the Maps SDK for Android overview page to provide users with this useful information. 

cc @langsmith

**Comment by langsmith** [comment]
Yes, it would be good to have a page on extrusions. Thanks for this ticket, @ZiZasaurus .

One cool trick that I've found is `fillExtrusionHeight(sum(literal(CONSTANT_NUMBER), get(PROPERTY_KEY)))));`. This increases the height of all extrusions but _still_ keeps their relative heights the same. This results in something like the GIF below, which is an adjustment of [the current demo app marathon route example](https://docs.mapbox.com/android/maps/examples/use-geojson-data-to-set-extrusion-height/)
![ezgif com-resize (3)](https://user-images.githubusercontent.com/4394910/70265924-40c9a200-1750-11ea-837e-31bfa625982a.gif)


Related artwork:
![Screen Shot 2019-12-05 at 10 45 02 AM](https://user-images.githubusercontent.com/4394910/70265714-d31d7600-174f-11ea-8f5f-1a1d806a1540.png)

![Screen Shot 2019-12-03 at 5 33 19 PM](https://user-images.githubusercontent.com/4394910/70265712-d31d7600-174f-11ea-9b6f-73ed2c9aa7e8.png)
![Screen Shot 2019-12-03 at 5 34 18 PM](https://user-images.githubusercontent.com/4394910/70265713-d31d7600-174f-11ea-8ee9-58f0e43db5df.png)
