### ISSUE TITLE
How to get a list of points of interest along a map in Maps SDK for Android?

### ISSUE THREAD

**Issue by MugheesButt** [mapbox/android-docs#1172]
Is it possible to get a list of points of interests i.e Gas Stations , School , Market etc along a route between origin and destination?

**Comment by langsmith** [comment]
Hi @MugheesButt , 

Please contact the Mapbox support team via https://support.mapbox.com/hc/en-us/requests/new?ticket_form_id=360000291231 for answers to your (implementation) questions.

Thanks!
