### ISSUE TITLE
add a generic API URL that redirects to latest javadoc

### ISSUE THREAD

**Issue by cammace** [mapbox/android-docs#123]
right now, the only way to link to javadoc is specifying the version number with it. Going to `https://www.mapbox.com/android-docs/api/map-sdk` should automatically redirect you for example.

**Comment by langsmith** [comment]
@colleenmcginnis 's https://github.com/mapbox/android-docs/pull/872 resolves this 💪 

https://docs.mapbox.com/android/api/map-sdk/ is a permalink to the latest Maps SDK API ref javadocs
