### ISSUE TITLE
Dead links on `Styling Map` page

### ISSUE THREAD

**Issue by ErinQuinn** [mapbox/android-docs#145]
**Document:** https://www.mapbox.com/android-docs/map-sdk/overview/styling-map/
**Error in doc:** broken links
**Correction:**

Hey team, noticing these two links in the first paragraph aren't live: 

![screen shot 2017-07-25 at 1 26 08 pm](https://user-images.githubusercontent.com/20598581/28585056-03f6ad5c-713d-11e7-8b73-960d706eafa5.png)

Think you want to point to https://www.mapbox.com/android-docs/map-sdk/overview/runtime-styling/ - not sure about the first one (Studio)

**Comment by langsmith** [comment]
Thanks @ErinQuinn
