### ISSUE TITLE
Conversion to Batfish

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/android-docs#146]
I've chatted a little bit with @cammace about this. Time to get real.

[Batfish](https://github.com/mapbox/batfish/) is at a point where it's ready to be battle-tested. (The documentation and testing still need a lot of work, but I kind of want to wait on that until we've battle-tested the API enough to really know it's going to work well.) We've already put Batfish into play for the React pages of the main Mapbox website. `android-docs` will be another important test for the library because it will take advantage of Batfish's Markdown features.

Because this repo already uses React, the conversion has a head start. The custom [Markdown loader](https://github.com/mapbox/android-docs/blob/47d279ace9b7ad8bf1fd65221740b859d72ef69f/loaders/markdown-loader/index.js) will introduce some hurdles, but I think it should all be pretty manageable. A number of features of the custom Markdown loader can be addressed with Batfish's jsxtreme-markdown syntax (which allows for the interpolation of JS expressions and JSX elements), and whatever else we need we should be able to handle with remark/rehype plugins.

@lshig and I could lead this conversion, with help and reviews from @cammace. Since I'm thinking now (contrary to earlier thoughts I had) that I'd like to finish this before we solidify Batfish's documentation and testing, we should be able to get started this week. Pending interruptions, I'm hoping we can finish within a few days of work.

@mapbox/android: do you have any concerns about this conversion, from Gatsby to Batfish? Any reasons we shouldn't get started? I've only chatted with @cammace about it so far.

cc @mayagao @mapbox/frontend

**Comment by zugaldia** [comment]
> @mapbox/android: do you have any concerns about this conversion, from Gatsby to Batfish? Any reasons we shouldn't get started? I've only chatted with @cammace about it so far.

@davidtheclark @cammace This is very exciting. @langsmith any concerns on your side? Otherwise let's 🚀 this.

**Comment by mayagao** [comment]
This sounds good to me. I want to introduce a couple of style changes but maybe it's better for me to do so after the conversion?

**Comment by davidtheclark** [comment]
> I want to introduce a couple of style changes but maybe it's better for me to do so after the conversion?

@mayagao: It wouldn't hurt to ticket those out now, and if it makes sense to implement any during the conversion we could do that.

**Comment by langsmith** [comment]
No concerns.

**Comment by davidtheclark** [comment]
The Batfish version is now live!
