### ISSUE TITLE
Pages lack meta descriptions

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/android-docs#153]
I don't see `<meta name="description">` on the HTML pages. My understanding is that this tag can help with SEO, so we should put the time into writing descriptions for each page.

**Comment by davidtheclark** [comment]
@cammace Assigning this one to you.

**Comment by davidtheclark** [comment]
Batfish branch includes a boilerplate description for every page (e.g. for Map SDK over view page: "Mapbox Android Map SDK overview").

@cammace and @colleenmcginnis it should be straightforward to update these if you want to, when you want to 👍

**Comment by cammace** [comment]
Noticed I still am assigned to this ticket. @colleenmcginnis @langsmith, I assume this still needs to be done?
