### ISSUE TITLE
Animate marker example link is incorrect

### ISSUE THREAD

**Issue by boundsj** [mapbox/android-docs#156]
**Document:** https://www.mapbox.com/android-docs/map-sdk/overview/annotations/
**Error in doc:** Example link for **Update a marker** points to BasicMarkerViewActivity.java
**Correction:** Link to https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/annotations/AnimatedMarkerActivity.java instead

cc @langsmith

**Comment by langsmith** [comment]
thanks @boundsj

**Comment by langsmith** [comment]
Fixed by #158
