### ISSUE TITLE
Header hierarchy skips h2

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/android-docs#165]
Most (or all?) of the pages skip from h1 to h3. For semantics (which lead to accessibility), we shouldn't skip a heading level like that.

I noticed that the help docs, which have the same typography, *do* include h2, which is styled slightly larger than h3.

@mayagao @cammace: Would you rather use h2's and style them like the current h3's, or use h2's and style then like help's h2's?

**Comment by davidtheclark** [comment]
I've also noticed some inconsistency — some pages using h2's and others skipping to h3's.

I think we should just take a pass through the code and set up the proper hierarchy. @cammace maybe you can do that, since you know the content well?

**Comment by cammace** [comment]
Let's keep things consistent between the help page and these docs and go with the same header formatting. Will run through the docs and fix up today.
