### ISSUE TITLE
Distinguishing section titles in sidebar nav is sometimes difficult

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/android-docs#170]
![screen shot 2017-08-04 at 12 59 18 pm](https://user-images.githubusercontent.com/628431/28984858-c8a4b764-7914-11e7-84a1-b79910a31d97.png)

It's pretty hard to tell where one item begins and another ends.

cc @mayagao

**Comment by davidtheclark** [comment]
cc @katmeng @mapbox/design

**Comment by katmeng** [comment]
@davidtheclark Can we add 6px spacing between the lines likes this:

<img width="252" alt="screen shot 2017-08-09 at 11 57 38 am" src="https://user-images.githubusercontent.com/26285898/29138929-f930b228-7cf9-11e7-8728-a30a5aa666e0.png">

**Comment by davidtheclark** [comment]
Closed by #187.
