### ISSUE TITLE
Mapbox Plugins "View changelog" link goes nowhere

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/android-docs#172]
![screen shot 2017-08-04 at 2 48 17 pm](https://user-images.githubusercontent.com/628431/28988302-08abb538-7924-11e7-9298-56cb224bc90d.png)

This changelog link does not go anywhere. @cammace: Where is it supposed to go? Or maybe there should be no link there?

**Comment by cammace** [comment]
I've opened a ticket in the plugins repo to add a changelog (see https://github.com/mapbox/mapbox-plugins-android/issues/75), we currently don't have one to link to.

**Comment by davidtheclark** [comment]
@cammace: I'd opt for removing the link on this page, then. That ok with you?

**Comment by cammace** [comment]
Yeah, I think the plugin repo will end up going with individual changelogs for each plugin rather than one for the entire project. We can always look into adding the link back later down the road.

**Comment by davidtheclark** [comment]
Fixed in the Batfish branch.
