### ISSUE TITLE
Navigation UI page is empty

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/android-docs#173]
![screen shot 2017-08-04 at 3 25 27 pm](https://user-images.githubusercontent.com/628431/28989302-35715104-7929-11e7-9a4f-49ce2e2a7f9b.png)

@cammace @mayagao: Should this page be deleted, or is it supposed to have content?

**Comment by cammace** [comment]
Yes, this is a page that should be deleted and must have gotten into a PR by accident.

**Comment by davidtheclark** [comment]
Thanks, @cammace. We'll remove it from the Batfish build.

**Comment by davidtheclark** [comment]
This is fixed in the Batfish branch.
