### ISSUE TITLE
Mapbox Services SDK overview page only one without Overview subheading

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/android-docs#174]
https://www.mapbox.com/android-docs/mapbox-services/overview/ is the only overview landing page, I think, that does not start with an Overview subheading.

Should we add one here, or remove it from the other places, @cammace, @colleenmcginnis?

**Comment by colleenmcginnis** [comment]
@davidtheclark I typically prefer not to use a heading between the page title and the first paragraph. I'd suggest removing 'Overview' from all landing pages, but I could get on board either way as long as they're consistent.

**Comment by langsmith** [comment]
Is this still an issue @colleenmcginnis ? 

`Overview` is still in the upper right hand corner of `Map SDK`, `Plugins`, etc. 
<img width="246" alt="screen shot 2017-10-10 at 4 58 58 pm" src="https://user-images.githubusercontent.com/4394910/31416170-57cd2eb6-addc-11e7-9e5c-6908ee567593.png">

but no pages seem to have `Overview` on them. Or maybe I'm misunderstanding the entire OP...

**Comment by colleenmcginnis** [comment]
I _think_ this was resolved @langsmith. IIRC the pages used to have a subheading like this (and I suggested removing them): 

![image](https://user-images.githubusercontent.com/10479155/31416318-1b614966-addd-11e7-8c8e-966d83db965e.png)

**Comment by langsmith** [comment]
Yea, that `Overview` no longers exists. Thanks @colleenmcginnis
