### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by colleenmcginnis** [mapbox/android-docs#178]
Make sure Google Analytics is set up for `mapbox.com/android-docs/`.

**Comment by mick** [comment]
@ericrwolfe was looking at fixing the segment integration for the docs here, that will start events flowing into GA as well.

**Comment by ericrwolfe** [comment]
I added segment in #179, but it looks like #157 will supersede it.

**Comment by davidtheclark** [comment]
Confirmed that this is now working on staging.
