### ISSUE TITLE
snippets/examples code switch for changing between Kotlin and Java

### ISSUE THREAD

**Issue by cammace** [mapbox/android-docs#180]
Similiar to iOS having both swift and objective-c language variants, Android has Kotlin and Java now and we need to make it easy to switch between examples and snippet languages.

cc: @zugaldia @davidtheclark

**Comment by davidtheclark** [comment]
🆒 

@mapbox/design — here's a good opportunity for us to create a good component pattern that will be reused across a lot of documentation.

**Comment by colleenmcginnis** [comment]
Noting that we do already use a similar strategy in `/help` for iOS content (for example, see https://www.mapbox.com/help/ios-dds-circle-layer/#initialize-a-map-view). It would be great to use a design that's fairly consistent (visually). Happy to adjust the style on the help page, too, if needed!

**Comment by katmeng** [comment]
@davidtheclark Thanks for bringing this up! I'm working on a toggle bar for the homepage that looks a tad different from the toggle bar in the `/help` ^ doc, really just a tad. The style should all be consistent though! Will think on this

**Comment by katmeng** [comment]
Also, this toggle style already exists in the install flow:

![screen shot 2017-08-10 at 4 45 50 pm](https://user-images.githubusercontent.com/26285898/29196821-e25a1efc-7deb-11e7-962a-086730a626f2.png)

**Comment by colleenmcginnis** [comment]
@katmeng happy to work on matching the code toggles on `/help` to whatever design you come up with here! I'd love for things to be consistent, but I don't have a strong opinion about what they look like.

**Comment by danswick** [comment]
Noting the new `example-transfuster` @davidtheclark built that we're currently using to put testable iOS code into iOS example pages. We should do something like this for android and use the same swift/obj-c toggle pattern for java/kotlin. 

https://github.com/mapbox/example-transfuser

**Comment by zugaldia** [comment]
@davidtheclark I'm looking at the docs for https://github.com/mapbox/example-transfuser and looks like it only targets the https://github.com/mapbox/help repo. Am I reading it right? Wondering if I can follow the same approach for this repo.

**Comment by davidtheclark** [comment]
@zugaldia: Yeah, I didn't have other use-cases in mind at the time, didn't know people would be transfusing examples to other places. We could certainly add the option to target different repositories. Would take a little bit of work. If you can open an issue in the repo explaining what you need that would help. Then we can make it happen.

**Comment by zugaldia** [comment]
@davidtheclark Totally makes sense, I just opened https://github.com/mapbox/example-transfuser/issues/4 to follow up. Thanks!

**Comment by colleenmcginnis** [comment]
The ability to toggle between Java and Kotlin is built into the updated site (#521). Once we have some Kotlin code snippets to work with, I'd be happy to help get this up and running! 

cc @riastrad @langsmith

**Comment by langsmith** [comment]
@colleenmcginnis , heads up that the Android team has decided to make Kotlin code snippets one of our sprint goals during the days before KotlinConf 2018 in early October. Nothing actionable right now, but I'll probably want to work with you in late September to set things up and get a better understanding of how the toggle works, so that the 📜 sprint goes smoothly .
