### ISSUE TITLE
Navigation broken on iPhone

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/android-docs#182]
![aug-08-2017 16-54-03](https://user-images.githubusercontent.com/628431/29099548-eb51c7f4-7c5a-11e7-9120-6e10fc73a515.gif)

The trigger is invisible. If you do manage to click it, you'll be sorry, because you won't be able to scroll to see the whole menu, and you won't be able to get out.

I think I have a solution for this in the Batfish branch.

**Comment by jfurrow** [comment]
The behavior is similar on my Android phone. You can scroll to the bottom (maybe due to the height of the screen?), but the menu obscures the trigger and you can't close it.

**Comment by davidtheclark** [comment]
Fixed in Batfish branch. I confirmed on iOS, @jfurrow confirmed on Android.
