### ISSUE TITLE
Padding below overview-header

### ISSUE THREAD

**Issue by cammace** [mapbox/android-docs#183]
When removing the header between the overview and beginning paragraph, it seems like a padding should be added to ease the flow between the two.

<img width="380" alt="screen shot 2017-08-09 at 12 39 46 am" src="https://user-images.githubusercontent.com/5652865/29105417-581047c2-7c9b-11e7-8763-b31356ce9195.png">

cc: @davidtheclark

**Comment by davidtheclark** [comment]
Fixed in Batfish branch.
