### ISSUE TITLE
Navigation UI page has no content and layout is messed up

### ISSUE THREAD

**Issue by langsmith** [mapbox/android-docs#184]
[Navigation SDK UI page](https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/) is empty and format is broken 👇 

![screen shot 2017-08-09 at 10 51 44 am](https://user-images.githubusercontent.com/4394910/29136061-ea7982f4-7cf0-11e7-84a0-35f0300b13b1.png)

cc @cammace

**Comment by davidtheclark** [comment]
@langsmith Fixed in the Batfish branch (https://github.com/mapbox/android-docs/issues/173)

**Comment by langsmith** [comment]
Oh, ok 👍  @davidtheclark
