### ISSUE TITLE
external link to ios-sdk doesn't work

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/android-docs#185]
Note the URL bar in this GIF:
![2017-08-09 16_07_06](https://user-images.githubusercontent.com/108094/29141629-fac4d966-7d1c-11e7-8a0f-a6a0bcde6f52.gif)

The URL bar changes to /ios-sdk/ put the page doesn't reload. Browser is chrome 60.

**Comment by davidtheclark** [comment]
👍 fixed in Batfish branch.
