### ISSUE TITLE
Expose Location layer plugin documentation better inside map sdk docs

### ISSUE THREAD

**Issue by cammace** [mapbox/android-docs#191]
LocationLayer plugin replaces the MyLocationView in the Map SDK. This might cause some confusion since it will now require an additional dependency to be added to a users app if they'd like to use it. Not sure if we want to expose this in the TOC or mention it in docs.

cc: @zugaldia

**Comment by langsmith** [comment]
@mapbox/android ,https://www.mapbox.com/android-docs/maps/overview/camera/#camera-and-device-location is where the LLP is mentioned in the maps section of our docs. Do you think that satisfies this ticket? Thoughts on where else the plugin could be mentioned? 

The extreme option is to create a separate left-hand sidebar drop-down section titled `Device location`. Its single page would basically point to https://www.mapbox.com/android-docs/plugins/overview/location-layer/

cc @colleenmcginnis

**Comment by zugaldia** [comment]
There're conversations about potentially bringing back that plugin to the Maps SDK. Whether that happens or not, I think this is such a common usecase that I'd like to keep a reference to the plugin in the main Maps section (besides the specific plugin section). How does iOS surface this feature? At a quick glance I only see https://www.mapbox.com/ios-sdk/maps/examples/user-location-annotation/.

**Comment by langsmith** [comment]
Yea, I don't see anything about device location anywhere in https://www.mapbox.com/ios-sdk/maps/overview/

**Comment by lilykaiser** [comment]
So sounds like the criteria for completion of this ticket is 
> keep a reference to the plugin in the main Maps section

per @zugaldia ? I am in favor. Let's do it.

**Comment by zugaldia** [comment]
I think it deserves its own section but I can also see it fitting with `Annotations`.

**Comment by langsmith** [comment]
Closing because [the plugin is being deprecated](https://github.com/mapbox/mapbox-plugins-android/issues/684#issuecomment-423180300)

@LukasPaczos 's ticket (https://github.com/mapbox/android-docs/issues/620) will help us track the most up-to-date docs for displaying location . Location display will be located in the maps section.
