### ISSUE TITLE
Update Navigation documentation

### ISSUE THREAD

**Issue by cammace** [mapbox/android-docs#215]
The documentation hasn't been updated since 0.4.0 and is in need of a refresh especially now that the UI is about to launch.

cc: @danesfeder @zugaldia @ericrwolfe @stephenlambe

**Comment by danswick** [comment]
Link to navigation javadoc now 404s: https://www.mapbox.com/android-docs/api/navigation/0.7.0/index.html

**Comment by danesfeder** [comment]
@danswick Just updated in #256 sorry about that 😅
