### ISSUE TITLE
Text incorrect for reverse geocoding 

### ISSUE THREAD

**Issue by malwoodsantoro** [mapbox/android-docs#220]
On [geocoder page](https://www.mapbox.com/android-docs/mapbox-services/overview/geocoder/) in android docs (beneath reverse geocoding) - 

"The process of turning a string address to a coordinate is called reverse geocoding."

_should be_

"The process of turning coordinates into a string address is called reverse geocoding."

**Comment by langsmith** [comment]
🙇  thanks @malwoodsantoro
