### ISSUE TITLE
Everything under 'API Reference' on geocoder page 404s 

### ISSUE THREAD

**Issue by malwoodsantoro** [mapbox/android-docs#221]
All of the below links 404 on [this page](https://www.mapbox.com/android-docs/mapbox-services/overview/geocoder/)

![screen shot 2017-09-25 at 2 54 44 pm](https://user-images.githubusercontent.com/19801577/30832896-bcc3ee36-a201-11e7-90ad-7b0e6c06aab3.png)

**Comment by cammace** [comment]
Should be fixed once https://github.com/mapbox/android-docs/pull/223#pullrequestreview-65295151 gets merged

**Comment by langsmith** [comment]
Confirmed that #223 fixed this issue
