### ISSUE TITLE
Position.fromLatLng() should be Position.fromLngLat()

### ISSUE THREAD

**Issue by malwoodsantoro** [mapbox/android-docs#222]
On the [navigation page](https://www.mapbox.com/android-docs/navigation/overview/#locationengine), in the code block for step 4 - according to [the docs](https://www.mapbox.com/android-docs/api/mapbox-java/libjava-core/2.0.0/com/mapbox/services/commons/models/Position.html#fromLngLat-double-double-), the method should be from**LngLat**().

**Comment by langsmith** [comment]
Thanks @malwoodsantoro  👍
