### ISSUE TITLE
Add section for location engine listener for use with drop-in Navigation UI

### ISSUE THREAD

**Issue by danswick** [mapbox/android-docs#233]
Ref: https://github.com/mapbox/mapbox-navigation-android/blob/master/libandroid-navigation-ui/src/main/java/com/mapbox/services/android/navigation/ui/v5/LocationViewModel.java#L79

**Comment by cammace** [comment]
Is this the documentation you are looking for? https://www.mapbox.com/android-docs/mapbox-services/overview/telemetry/#locationengine. In either case, maybe we can make the navigation docs more clear

**Comment by langsmith** [comment]
@danesfeder ,  https://www.mapbox.com/android-docs/navigation/overview/#locationengine now exists, which basically points to https://www.mapbox.com/android-docs/core/overview/#locationengine .  Do these links satisfy OP or do you feel that there is still missing information regarding location/navUI?

**Comment by danesfeder** [comment]
@langsmith I believe so - noting that https://www.mapbox.com/android-docs/core/overview/#locationengine can be updated in a few spots as `LostLocationEngine` isn't provided by the core location library anymore

**Comment by danswick** [comment]
Oh wow, sorry for dropping out of this thread, y'all. @langsmith I would say that does indeed satisfy the OP. Closing here!

**Comment by langsmith** [comment]
Thanks all. I ticketed @danesfeder 's `LocationEngine` update suggestion at #581
