### ISSUE TITLE
Updating android-sdk/overview copy

### ISSUE THREAD

**Issue by Lndsay** [mapbox/android-docs#238]
We are going to update the copy and slightly adjust the layout of https://www.mapbox.com/android-docs/map-sdk/overview/ to better highlight instillation instructions. 

**Plan:**
+ [ ] Remove duplicate installation instructions + replace with new copy
+ [ ] Remove the `begin installation instructions` button 
+ [ ] Add a new section similar to the `getting started` section of https://www.mapbox.com/ios-sdk/ 

**Needs:** 
+ Copy to replace the current `Install the Map SDK` section 
+ Site changes 

**Who:**
+ copy: @langsmith @lndsay 
+ site: @angel

Timeline: Next week, if possible

**Comment by langsmith** [comment]
Is this moving forward @Lndsay ? Current status?

**Comment by Lndsay** [comment]
Paused for now, will reopen as needed
