### ISSUE TITLE
Update location docs for 5.2.0

### ISSUE THREAD

**Issue by langsmith** [mapbox/android-docs#250]
Based on [this `gl-native` conversation thread](https://github.com/mapbox/mapbox-gl-native/issues/10335#issuecomment-343142366)

cc @Guardiola31337 @electrostat @zugaldia

**Comment by Guardiola31337** [comment]
Thanks @langsmith for tracking this.

We should document that now `LocationSource` is `@Deprecated` and the location provider is optional, meaning that the users will need to include `Lost` or `Google Play Services` dependencies explicitly in their `build.gradle` files if they want to use `LocationEngine` (if they don't include any of those, `Android` is the default engine).
`MarkerView` is now also `@Deprecated` so it'd be great to document what they need to do to implement the behaviors with runtime styling and show examples on how to migrate them.
Same with `MyLocationView` which is `@Deprecated` in favor of the `LocationLayer` plugin.

@tobrun am I missing something?

**Comment by langsmith** [comment]
> - [ ] LocationSource is @Deprecated and the location provider is optional, meaning that the users will need to include Lost or Google Play Services dependencies explicitly in their build.gradle files if they want to use LocationEngine (if they don't include any of those, Android is the default engine).

Not sure what's still true in☝️ given all of the [`liblocation`](https://github.com/mapbox/mapbox-events-android/tree/master/liblocation/src/main/java/com/mapbox/android/core/location) changes since @Guardiola31337 's ticket was written in November. However, I've got [this open pr](https://github.com/mapbox/android-docs/pull/370) that makes some tweaks to the page...which will eventually be renamed to `Core Libraries` and be updated at a later date( https://github.com/mapbox/android-docs/issues/354#issuecomment-373486676 )

> - [ ] MarkerView is now also @Deprecated so it'd be great to document what they need to do to implement the behaviors with runtime styling and show examples on how to migrate them.

There's https://blog.mapbox.com/a-guide-to-the-android-symbollayer-api-5daac7b66f2c , but I've 
ticketed the fact that we need more symbol layer docs in `android-docs` https://github.com/mapbox/android-docs/issues/307


> - [x] MyLocationView which is @Deprecated in favor of the LocationLayer plugin 

Mentioned at the end of the first paragraph at https://www.mapbox.com/android-docs/plugins/overview/location-layer/ and I think we've got enough docs in various places that people should now discover/know that the location layer plugin is the best option.

**Comment by zugaldia** [comment]
cc: @mapbox/maps-android for comment on the `MarkerView` and `MyLocationView` components documentation.

**Comment by LukasPaczos** [comment]
@langsmith Actually, with `6.0.0` of the Maps SDK all location services (like `MyLocationView` and `LocationSource`) will be removed. I think we can emphasize that the `LocationLayerPlugin` is the only option going forward and eventually remove it from the doc.
When it comes to `MarkerView`s, they'll share location services' fate when project pinpoint, with easier markers manipulations on a layer, lands.

**Comment by langsmith** [comment]
Great, thanks for the updated info @LukasPaczos 🚀

**Comment by langsmith** [comment]
All 3 checkboxes above have been addressed. Our docs have much more mentions of LLP, `LocationEngine`, and SymboLayer icons.
