### ISSUE TITLE
Add transitive dependencies

### ISSUE THREAD

**Issue by zugaldia** [mapbox/android-docs#265]
Since 5.2.0 we're now recommending the following line to include our SDK on `build.gradle`:

```
  implementation 'com.mapbox.mapboxsdk:mapbox-android-sdk:5.2.0@aar'
```

However this fails because it doesn't include the transitive dependencies (we used to explicitely include that in the past). We need to either:

1. Reintroduce the `transitive=true` keyword.
2. Or, make our SDK automatically include the transitive dependencies (is that possible, @tobrun?)

cc: @langsmith

**Comment by langsmith** [comment]
@zugaldia 

The following two prs address this:

https://github.com/mapbox/android-docs/pull/264/files

https://github.com/mapbox/www.mapbox.com/pull/2603/files

**Comment by zugaldia** [comment]
@langsmith Thank you, and apologies I missed those. Just went ahead and approved both.
