### ISSUE TITLE
[example request] Minimal InfoWindow with symbol layer example

### ISSUE THREAD

**Issue by danswick** [mapbox/android-docs#271]
We have @tobrun's super cool RecyclerView example in labs now (https://github.com/mapbox/mapbox-android-demo/pull/538), but it would be particularly helpful to have a minimal example that mirrors our exiting [MarkerOptions InfoWindow example](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/annotations/DrawMarkerActivity.java) ("Draw a Marker"), but using SymbolLayers instead. We've been getting a ton of questions about this lately, especially as I've been recommending users use SymbolLayers more often.

**Comment by langsmith** [comment]
Closing this ticket because I think this is better suited for the demo app than for android docs. Ticketed in demo app repo at https://github.com/mapbox/mapbox-android-demo/issues/651 and conversation can continue on there.
