### ISSUE TITLE
Broken link to location layer API reference 

### ISSUE THREAD

**Issue by danswick** [mapbox/android-docs#273]
![image](https://user-images.githubusercontent.com/2365503/33695534-afda1620-dab2-11e7-8931-b7b10e9e2fb5.png)

Points to https://www.mapbox.com/android-docs/api/plugins/locationlayer/0.2.0/index.html, which does not exist.

**Comment by langsmith** [comment]
The blue `Location Layer` link in OP screenshot now points to https://www.mapbox.com/android-docs/api/plugins/locationlayer/0.3.0/index.html
