### ISSUE TITLE
Update the navigation documentation with when to properly call startNavigation

### ISSUE THREAD

**Issue by devotaaabel** [mapbox/android-docs#282]
I think we need to add more information to the documentation about when the user can safely add listeners and start navigation.

Refer to this ticket:
https://github.com/mapbox/mapbox-navigation-android/pull/620

**Comment by langsmith** [comment]
@mapbox/navigation-android , would you say that this is ✔️or no? 

https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/

**Comment by langsmith** [comment]
Closing as @devotaaabel has said that the current docs are 👍 for this
