### ISSUE TITLE
Broken Mapbox Services API Reference links

### ISSUE THREAD

**Issue by colleenmcginnis** [mapbox/android-docs#294]
All the links in the **API Reference** popover on [this page](https://www.mapbox.com/android-docs/mapbox-services/overview/
) are 404'ing.

![image](https://user-images.githubusercontent.com/10479155/35422351-0df1e352-01fd-11e8-8b54-5c3712e3a5bf.png)

cc @langsmith

**Comment by langsmith** [comment]
Yes,  because the make file in mapbox-java is now mysteriously missing a make javadocs function. I guess I can revert the MAS version number in this repo's constants file until @cammace and I figure out javadocs generation.

**Comment by langsmith** [comment]
Found some past `make javadoc` code to work off of. Still trying to figure out how to adjust it to account for our major 3.0.0 folder (name) restructuring...


https://github.com/mapbox/mapbox-java/commit/2c7cdab137b89cdcbdd31663249a789d99a4d891#diff-b67911656ef5d18c4ae36cb6741b7965L29

**Comment by colleenmcginnis** [comment]
@langsmith some of these links were fixed 🎉 but some are still broken 😕 :

- [mapbox-java-services](https://www.mapbox.com/android-docs/api/mapbox-java/libjava-services/3.0.0-beta.2/index.html) 
- [mapbox-java-services-rx](https://www.mapbox.com/android-docs/api/mapbox-java/libjava-services-rx/3.0.0-beta.2/index.html)
- [mapbox-android-telemetry](https://www.mapbox.com/android-docs/api/mapbox-java/libandroid-telemetry/3.0.0-beta.2/index.html)
- [mapbox-android-ui](https://www.mapbox.com/android-docs/api/mapbox-java/libandroid-ui/3.0.0-beta.2/index.html)

**Comment by langsmith** [comment]
I know :(  This is all stemming from our major changes to MAS structure with 3.x

These currently broken links will no longer appear once https://github.com/mapbox/android-docs/pull/304 lands. I believe I've correctly handled the 3.x naming changes appropriately in that pr, in that there are now only 4 MAS modules with API Reference docs.
