### ISSUE TITLE
Link to "runtime animations" tutorial goes to LineLayer activity

### ISSUE THREAD

**Issue by danswick** [mapbox/android-docs#301]
The tutorial card under https://www.mapbox.com/android-docs/map-sdk/overview/runtime-styling/ leads to the LineLayer example instead of a runtime animations tutorial. I believe it's supposed to point to https://www.mapbox.com/help/android-runtime-styling-intro/, but am unsure because that tutorial does not include animations.

**Comment by langsmith** [comment]
Thanks @danswick . Will fix today
