### ISSUE TITLE
Update telemetry section docs

### ISSUE THREAD

**Issue by langsmith** [mapbox/android-docs#354]
#286 partitioned a new section for telemetry in Android docs, but it just copied old docs over to its own section. This ticket is to track the work needed to update https://www.mapbox.com/android-docs/telemetry/overview/

cc @electrostat @zugaldia @Guardiola31337

**Comment by zugaldia** [comment]
By looking that the current content I suggest we rename this section to "Core Libraries" or something along those lines as this is what this page is actually covering (modules `libcore` and `liblocation` in https://github.com/mapbox/mapbox-events-android).

We'd need to include:
- `ConnectivityListener` and `ConnectivityReceiver` from `libcore`.
- [Location](https://github.com/mapbox/mapbox-events-android/tree/master/liblocation/src/main/java/com/mapbox/android/core/location) and [Permissions](https://github.com/mapbox/mapbox-events-android/tree/master/liblocation/src/main/java/com/mapbox/android/core/permissions) components from `liblocation`.

No need to include any docs from the `libtelemetry` module at this point.
