### ISSUE TITLE
Adjust Mapbox Java Service class names and code samples

### ISSUE THREAD

**Issue by langsmith** [mapbox/android-docs#356]
Need to find and change the names of updated classes within Mapbox Java Services. For example,     https://www.mapbox.com/android-docs/mapbox-services/overview/directions-matrix/
 still has `DirectionsMatrixResponse` in the code example when the class is actually now named `MatrixResponse`. Off the top of my head, I know that similar changes are needed for the Optimization API.

**Comment by cammace** [comment]
Awesome catch @langsmith, perhaps we should add this to the list of items we want to hit during our sprint.

**Comment by langsmith** [comment]
Added to the sprint ticket. I might just knock this out before the sprint, depending on how much there is to adjust. We'll see.
