### ISSUE TITLE
Add demo app Play Store badge (to sidebar?)

### ISSUE THREAD

**Issue by langsmith** [mapbox/android-docs#364]
@zugaldia had mentioned that it could be good to add the Play Store badge to the Android docs sidebar like how the iOS docs portal has its App Store badge 👇 

![screen shot 2018-03-15 at 11 02 38 am](https://user-images.githubusercontent.com/4394910/37482071-99bd15e6-2840-11e8-985d-fe597301eb47.png)

**Comment by cammace** [comment]
This is something that should be done when the new documentation design sprint happens.

**Comment by langsmith** [comment]
cc @mgosline and @colleenmcginnis because I believe you two are looking into sidebar redesign

**Comment by langsmith** [comment]
Suuuuuuuper low priority but I'd be interested to know whether this is an option now that the new docs site redesign has rolled out.

**Comment by langsmith** [comment]
Closing because I don't realistically see a place where a persistent badge could be added for just the Android docs while also keeping visually continuity with other platforms. If someone disagrees and wants to move forward on this, please re-open the ticket 🙇

**Comment by zugaldia** [comment]
Thank you @langsmith for putting some thinking into this. Why not simply adding the badge under the paragraph that mentions the app?

> The Mapbox Maps SDK for Android is an open source toolset for displaying maps inside of your Android application. Mapbox's demo app on the Google Play Store includes many examples of how to use the Mapbox Maps SDK for Android. Various pages in this documentation reference the demo app's examples as well.
