### ISSUE TITLE
Change all Mapbox Java Services references to "Mapbox Java SDK"

### ISSUE THREAD

**Issue by langsmith** [mapbox/android-docs#382]
Change all references of Mapbox Java (Services) to `Mapbox Java SDK`.

**Comment by 1ec5** [comment]
Does this also cover the Android-specific libraries in the mapbox-java repository, which aren’t applicable to all Java environments?

**Comment by langsmith** [comment]
I made this ticket for changing high-level mentions of https://github.com/mapbox/mapbox-java on pages like https://www.mapbox.com/android-docs/mapbox-services/overview/. As in, header says `Mapbox Services SDK` but then "Mapbox Java is an open source..." at the start of the overview paragraph. 

I've made a ticket about the topic you mentioned in your comment above, so that we can keep it on our radar https://github.com/mapbox/android-docs/issues/383

![screen shot 2018-03-26 at 1 03 59 pm](https://user-images.githubusercontent.com/4394910/37920894-2a9b3a80-30f6-11e8-85b9-971c9b651143.png)

**Comment by zugaldia** [comment]
> Does this also cover the Android-specific libraries in the mapbox-java repository, which aren’t applicable to all Java environments?

@1ec5 Since ~MAS~ Mapbox Java SDK 3.x all code is 100% Java. Any Android-specific code was moved to other repos (mostly telemetry and plugins).

**Comment by 1ec5** [comment]
Updated a couple references in the OpenStreetMap Wiki:

https://wiki.openstreetmap.org/wiki/Mapbox_GL
https://wiki.openstreetmap.org/wiki/Open_Source_Routing_Machine

**Comment by langsmith** [comment]
🤜 🤛  @1ec5
