### ISSUE TITLE
Customer docs feedback on navigation, camera, location

### ISSUE THREAD

**Issue by ericdeveloper** [mapbox/android-docs#406]
Passing along documentation feedback from a customer who is building a system that allows them to show a routeline and update a user's location. 

>The [location doc here](https://www.mapbox.com/android-docs/plugins/overview/location-layer/) doesn’t really show the options available for viewing current location. I can reach the example but that is just code. What can I do about viewing angle, moving the position without moving the map, moving the map while centering the position? There is also no link from the location plugin to the example of the [navigation app which is in the navigation sdk](https://www.mapbox.com/help/android-navigation-sdk/#display-user-location). On top of that the [camera is in the Maps SDK area](https://www.mapbox.com/android-docs/map-sdk/overview/camera/). All of these are interrelated features spread out over different domains of the documentation.

cc: @mapbox/docs

**Comment by langsmith** [comment]
Great, thanks for the feedback @ericdeveloper .

**Comment by langsmith** [comment]
fyi @ericdeveloper , @danesfeder put together these great docs about the improved nav camera, location, tracking, etc. https://github.com/mapbox/mapbox-plugins-android/releases/tag/v0.5.0-location-layer        I'm going to eventually figure out how to work them into https://www.mapbox.com/android-docs/plugins/overview/location-layer/
