### ISSUE TITLE
Broken link in NavigationSDK#LocationEngine docs

### ISSUE THREAD

**Issue by samfader** [mapbox/android-docs#407]
Clicking `LocationEngine` results in a 404 [here](https://www.mapbox.com/android-docs/navigation/overview/#locationengine). I'm happy to fix this - I just got everything up and running locally - but not sure what the proper link should be.

**Comment by langsmith** [comment]
It should go to https://www.mapbox.com/android-docs/core/overview/#locationengine but I'll fix it in an upcoming pr because I need to add some other `locationEngine` stuff anyways. Thanks @samfader 🚀

**Comment by langsmith** [comment]
Resolved with #411
