### ISSUE TITLE
Expressions reference

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/android-docs#417]
I'd be great to have Expressions reference somewhere in the Android docs page, for example, in the runtime styling tab. A basic example and links to the style spec + demo app should be enough.

/cc @langsmith @tobrun

**Comment by langsmith** [comment]
cc @noemiwalzebuck because you'd asked about expressions docs

**Comment by langsmith** [comment]
- [ ] Intro about how we separate data from styling
- [ ] Example how to differentiate feature styling with expressions
- [ ] High level overview of expressions

Perhaps start with the “heavy hitters” for explanations/examples? For expressions like:

- ​​`get`
- ​​`match`
- ​​`switchCase`
- ​​`equal`
- ​​`literal`

**Comment by cammace** [comment]
Writing about `raw` expressions (when it becomes available) and adding info about colors would be useful too (see https://github.com/mapbox/mapbox-plugins-android/pull/526#issuecomment-391077782). I'd love to write this doc if no ones started yet just to familiarize myself with expressions even further.

**Comment by lilykaiser** [comment]
Let's scope this ticket to referencing the resources we already have available: the javadocs for the Expression class and the examples in the DDS folder
