### ISSUE TITLE
API Reference link 404s for new 6.0.1 release

### ISSUE THREAD

**Issue by samfader** [mapbox/android-docs#418]
Clicking API Reference [here](https://www.mapbox.com/android-docs/map-sdk/overview/) leads to [here](https://www.mapbox.com/android-docs/api/map-sdk/6.0.1/index.html) which 404s. Happy to try to fix if given the correct URL, and apologies if this is already in the pipeline!

**Comment by langsmith** [comment]
😵 It never ends. Thanks @samfader . Must've forgotten to add 6.0.1 Maps SDK javadocs. Added them in https://github.com/mapbox/android-docs/pull/428, so this issue will be resolved.

**Comment by langsmith** [comment]
Yep, confirmed that added docs have resolved this broken link issue
