### ISSUE TITLE
Update Navigation section once navigation is its own SDK

### ISSUE THREAD

**Issue by langsmith** [mapbox/android-docs#42]
Sentences such as "Make sure your Android project includes the `mapbox-android-ui` dependency to gain full access to the navigation APIs." will no longer be correct....

**Comment by ericrwolfe** [comment]
Looks like the transfer is just about done: https://github.com/mapbox/mapbox-navigation-android/issues/4

In addition to `Add description and installation instructions to README` in that ticket, let's also make sure to add in installation instructions similar to the Maps SDK and MAS:
<img width="628" alt="screen shot 2017-04-20 at 11 05 31 am" src="https://cloud.githubusercontent.com/assets/664805/25245462/528e1b96-25b9-11e7-95e9-219a0a008b05.png">

**Comment by langsmith** [comment]
@ericrwolfe , I'm exactly sure what you mean by "let's also make sure to add in installation instructions similar to the Maps SDK and MAS:"...

**Comment by ericrwolfe** [comment]
Yup, so if you look at the sidebar and page content, the Maps SDK and Mapbox Services contain documentation around the following that would be great to carry over to the Mapbox Navigation documentation:

* API Reference
* Access tokens
* Installation
* Gradle
* Maven

**Comment by langsmith** [comment]
Got it, got it. Will get around to that re-arrangement soon

**Comment by cammace** [comment]
Javadoc also needs to be produced, added to the API folder, and linked in the API Reference section.

**Comment by cammace** [comment]
With the new doc design, navigation's separated into its own section.
