### ISSUE TITLE
Add a `latest` redirect to all SDKs

### ISSUE THREAD

**Issue by zugaldia** [mapbox/android-docs#47]
Instead of hardcoding a version number (https://www.mapbox.com/android-docs/mapbox-navigation/0.1/navigation/) in pages like https://www.mapbox.com/navigation-sdk, we should be able to link to an URL like:

```
https://www.mapbox.com/android-docs/mapbox-navigation/latest/navigation/
```

Also, we shouldn't need to have two `navigation` words in there. Could this be simplified to the following?

```
https://www.mapbox.com/android-docs/mapbox-navigation/latest
```

Or even:

```
https://www.mapbox.com/android-docs/navigation/latest
```

The same should apply to all SDKs.

cc: @langsmith @cammace

**Comment by cammace** [comment]
ideally, ever SDK page should first land you to a `getting started` guide. I admit, the positioning of the versioning number was an oversight and should be fixed ASAP (this requires reorganizing of the directories inside the project).

**Comment by 1ec5** [comment]
Would we create redirects for each individual page under each library, like https://www.mapbox.com/android-docs/mapbox-services/latest/directions-matrix/? Unfortunately, I don’t think the publishing tool supports rewrite rules.

**Comment by langsmith** [comment]
@cammace , [your PR from a couple of days ago](https://github.com/mapbox/android-docs/pull/52) addresses this ticket, correct?

**Comment by cammace** [comment]
Yep, thanks!
