### ISSUE TITLE
Add PR testing for spelling, unused dependencies, etc.

### ISSUE THREAD

**Issue by cammace** [mapbox/android-docs#5]
List of potential checks:
- [ ] Unused dependencies: https://github.com/depcheck/depcheck
- [x] Retext: https://github.com/mapbox/retext-mapbox-standard
- [ ] Check for dependency updates: https://github.com/tjunnone/npm-check-updates

**Comment by langsmith** [comment]
The great work from the entire @mapbox/docs has now got this repo's prs going through serious testing whenever a commit is made. Spelling gets checked, we've got a stable versions file, etc.
