### ISSUE TITLE
Add geocoding example

### ISSUE THREAD

**Issue by tobrun** [mapbox/android-docs#513]
When visiting the [examples page](https://www.mapbox.com/android-docs/java-sdk/examples) of mapbox-java, I'm missing an example for geocoding.

**Comment by langsmith** [comment]
Thanks. Demo app could stand a geocoding example ([ticketed here](https://github.com/mapbox/mapbox-android-demo/issues/742))

Related:

- The `LocationPickerActivity` (which currently lives in the `labs` package), [does reverse geocoding](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/LocationPickerActivity.java)

- https://github.com/mapbox/mapbox-android-demo/issues/715
