### ISSUE TITLE
Add NavigationView Theme diagram to define color organization

### ISSUE THREAD

**Issue by danesfeder** [mapbox/android-docs#519]
We offer the ability to change a lot of the colors / attributes of the `NavigationView` in the Navigation SDK.  We should create a diagram that illustrates where each attribute aligns to the actual view when it's inflated. 

https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/#styling-the-navigationview

**Comment by akitchen** [comment]
Can we start with a one-off version of this, before getting into an automated technical solution?
