### ISSUE TITLE
Plugins and core libraries are hard to discover

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/android-docs#550]
Unless there is another way, the only one I was able to find was:

Navigating to Maps SDK documentation -> clicking the spinner -> scrolling down, which I did by accident and otherwise would've never guessed it's scrollable -> found plugins docs

I knew what I was looking for and it was really hard to find regardless. I think it would be great if we had  a reference in https://www.mapbox.com/developers/ which is loaded after we click `More documentation` in the `Documentation` tab and a persistent scrollbar in the docs navigation spinner.

/cc @colleenmcginnis @langsmith @danesfeder

**Comment by langsmith** [comment]
thanks @LukasPaczos . I had the same feedback for @colleenmcginnis yesterday and it sounds like others have had the same concern about "hidden" sections in the docs navigation spinner dropdown menu.

**Comment by colleenmcginnis** [comment]
#604 should help with discoverability. The new dropdown menu (1) uses the `viewport-almost` assembly class so the menu's height will be as large as is appropriate for the current viewport and (2) displays a scroll bar by default (not only when scrolling). 

![image](https://user-images.githubusercontent.com/10479155/45328279-1cacf000-b510-11e8-8f8f-e18f669af578.png)
