### ISSUE TITLE
Turf API reference link is broken

### ISSUE THREAD

**Issue by 1ec5** [mapbox/android-docs#552]
The [Overview](https://www.mapbox.com/android-docs/java/overview/) page’s “API reference” menu links to this [mapbox-java-turf](https://www.mapbox.com/android-docs/api/mapbox-java/libjava-turf/3.3.0/index.html) URL that doesn’t exist.

/cc @langsmith @colleenmcginnis

**Comment by langsmith** [comment]
Thanks @1ec5 , I will fix this.
