### ISSUE TITLE
Traffic Plugin Doc

### ISSUE THREAD

**Issue by cammace** [mapbox/android-docs#56]
The plugins have generally been documented but we need to have a specific doc for each plugin. Let's start with the traffic plugin.

cc: @mapbox/android

**Comment by langsmith** [comment]
What do you think the structure should be @cammace ? I'm thinking each plugin would have it's own sidebar section (within the umbrella Plugins toolbar section) like MAS has Directions Matrix, Geocoder, etc.?

![screen shot 2017-05-18 at 5 38 45 pm](https://cloud.githubusercontent.com/assets/4394910/26228729/eb404830-3bf0-11e7-92e4-71c56e93e166.png)

**Comment by cammace** [comment]
Exactly what I was thinking

**Comment by cammace** [comment]
Traffic plugins well documented at this point, closing.
