### ISSUE TITLE
Add snapshot information to map sdk readme file

### ISSUE THREAD

**Issue by cammace** [mapbox/android-docs#58]
In the new docs, we show how to install the latest stable version of the map sdk and leave instructions to install snapshots inside the readme files. The map SDKs readme lacks this information.

@langsmith would you be able to add this info inside the readme?

**Comment by langsmith** [comment]
[This `mapbox-gl-native` pr](https://github.com/mapbox/mapbox-gl-native/pull/9636) adds snapshot info to the `mapbox-gl-native` Android readme

**Comment by aboshab2** [comment]
بتاريخ ٢٠١٧/٠٧‏/٢٧ ٨:٥٨ م، كتب "Langston Smith" <notifications@github.com>:

**Comment by langsmith** [comment]
Closing because linked pr above resolves this. Please re-open or comment if you disagree.
