### ISSUE TITLE
LocationEngine Updates

### ISSUE THREAD

**Issue by danesfeder** [mapbox/android-docs#580]
https://www.mapbox.com/android-docs/core/overview/#locationengine can be updated in a few spots as `LostLocationEngine` isn't provided by the core location library anymore and the code snippets are incorrect for `AndroidLocationEngine` given the issue we just found in the LLP:

```
LocationEngine locationEngine = new LocationEngineProvider(this).obtainBestLocationEngineAvailable();
locationEngine.activate();
locationEngine.addLocationEngineListener(new LocationEngineListener() {
  @Override
  public void onConnected() {
    locationEngine.requestLocationUpdates();
  }
 
  @Override
  public void onLocationChanged(Location location) {
 
  }
});
```

cc @LukasPaczos @Guardiola31337

**Comment by LukasPaczos** [comment]
LLP issue for reference https://github.com/mapbox/mapbox-plugins-android/issues/601.
