### ISSUE TITLE
Update location engine section

### ISSUE THREAD

**Issue by langsmith** [mapbox/android-docs#581]
Per @danesfeder 's comment at https://github.com/mapbox/android-docs/issues/233#issuecomment-407046919

> https://www.mapbox.com/android-docs/core/overview/#locationengine can be updated in a few spots as LostLocationEngine isn't provided by the core location library anymore

**Comment by danesfeder** [comment]
@langsmith I opened https://github.com/mapbox/android-docs/issues/580 as well - don't mind closing if you'd rather track here

**Comment by langsmith** [comment]
Must've missed that somehow @danesfeder . We can track there.
