### ISSUE TITLE
`Install` button not working on Nav SDK for Android

### ISSUE THREAD

**Issue by jseppi** [mapbox/android-docs#586]
Reported by @domlet originally:

**Type of issue**

Bug.

**Priority**

Requires immediate attention.

**Description**

On https://www.mapbox.com/android-docs/navigation/overview/

Trying to click ![screenshot 2018-08-01 09 48 12](https://user-images.githubusercontent.com/6026447/43535903-052cc032-9570-11e8-8f6c-cf66462a3610.png) button at top of page

Not going anywhere.

Thanks!

**Comment by langsmith** [comment]
Any progress on this @colleenmcginnis ?

**Comment by colleenmcginnis** [comment]
This will be fixed in #604.

**Comment by langsmith** [comment]
k, cool

**Comment by colleenmcginnis** [comment]
I removed the button in #604. Installation instructions are below in the text. 
![image](https://user-images.githubusercontent.com/10479155/45328041-e1f68800-b50e-11e8-99a9-0f7ede77ac67.png)
