### ISSUE TITLE
API reference link not working on mobile

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/android-docs#593]
API reference link not working on mobile 👀 

![api_reference_link_not_working_on_mobile](https://user-images.githubusercontent.com/1668582/43842417-99e6217c-9b25-11e8-99cf-beddff6432d0.gif)

No `hover` on mobile.

cc @colleenmcginnis

**Comment by Guardiola31337** [comment]
Desktop behavior 👀 

![api_reference_desktop_behavior](https://user-images.githubusercontent.com/1668582/43842751-4e1a7724-9b26-11e8-9452-23e48094dd26.png)

**Comment by langsmith** [comment]
Works on desktop

https://www.mapbox.com/android-docs/navigation/overview/

https://www.mapbox.com/android-docs/api/navigation-sdk/navigation/0.17.0/index.html

**Comment by langsmith** [comment]
@colleenmcginnis , will #604 fix this too?

**Comment by colleenmcginnis** [comment]
It doesn't right now @langsmith, but it sets me up to make this fix. I can follow up with another PR on Friday or Monday.

**Comment by colleenmcginnis** [comment]
This should be fixed for the Navigation SDK, Java SDK, and Plugins docs in #604. If you continue to see any issues, please reopen this issue! 
![image](https://user-images.githubusercontent.com/10479155/45328082-19653480-b50f-11e8-9f97-71814cf554c8.png)
