### ISSUE TITLE
Fix Outdated Code for NavigationViewOptions

### ISSUE THREAD

**Issue by riastrad** [mapbox/android-docs#626]
In the [Navigation SDK for Android](https://www.mapbox.com/android-docs/navigation/overview/navigation-ui/#navigationview-activity-example) documentation - specifically in **Step 2** of the NavigationView Activity Example - there is code that follows an outdated API pattern:
```
@Override
public void onNavigationReady() {
  NavigationViewOptions options = NavigationViewOptions.builder()
    .origin(origin)
    .destination(destination)
    .awsPoolId(awsPoolId)
    .shouldSimulateRoute(simulateRoute)
    .build();
 
  navigationView.startNavigation(options);
}
```

Calls to `.origin()`, `.destination()`, and `.awsPoolId()` will cause the current version of the SDK to fail if used. In light of this, I vote we update this code block. 🙂

**Comment by langsmith** [comment]
I've started in #637 . Would really love some help with code tweaks on that pr/branch by @mapbox/navigation-android if ya'll get a chance 🙏  I started to dive into the current nav code to investigate but had a rough time trying to traverse the SDK with its new structure/naming/terminology

**Comment by danesfeder** [comment]
@langsmith sure thing, I'll review today!

**Comment by langsmith** [comment]
thank you @danesfeder . I just realized that I could've looked at the Nav SDK test app for current implementation 😭 Will just learn from your additions this time though
