### ISSUE TITLE
Create MapView lifecycle chart?

### ISSUE THREAD

**Issue by langsmith** [mapbox/android-docs#630]
cc @mapbox/maps-android 

The table at https://www.mapbox.com/android-docs/maps/overview/events/#map-change-events _does_ exist. I think further work could be done to make it clear which events fire in which order/situations. The lifecycle(s) might be too complex to do in a chart, but I wanted to bring it up at least. Something similar to https://www.google.com/search?q=android+activity+lifecycle&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjTvrb7i8jdAhUGj1QKHRzMDi0Q_AUIDigB&biw=1309&bih=730&dpr=2.2#imgrc=uKZMRnhCvKMxAM:

![android-activity-lifecycle-01](https://user-images.githubusercontent.com/4394910/45850073-8768e300-bce9-11e8-8f98-838e9b383161.png)

I've set up a very rough start in a Sketch file 👇 . Perhaps design team could eventually ✨ it for us

**Comment by langsmith** [comment]
actually, images are frowned upon by our documentation style guide ( @colleenmcginnis :gavel: )

an ordered text list of `MapView` events could work

**Comment by langsmith** [comment]
What I came up with for a basic map load order based on looking at logcat of `MapChangeActivity` in the Maps SDK test app. Can convert to text later


![group 2](https://user-images.githubusercontent.com/4394910/45852860-01539900-bcf7-11e8-98ca-cd795851a954.png)

**Comment by langsmith** [comment]
Basic map style switch ( `streets` to `dark`) based on `MapChangeActivity`. I added a style switch button to the activity's XML layout to produce this

![group](https://user-images.githubusercontent.com/4394910/45852906-4e376f80-bcf7-11e8-82ce-95b6c83dfb23.png)

**Comment by langsmith** [comment]
cc @macro-shen who mentioned the desire for better docs about the `MapView` lifecycle

**Comment by zugaldia** [comment]
cc: @mapbox/maps-ios because the lifecycle should be the same on both platforms. If we built this ordered table, we could add it to `/ios` docs as well. Or is there anything like this already published?

**Comment by julianrex** [comment]
Not that I'm aware of. The closest thing in iOS is probably the `MGLMapViewDelegate` documentation e.g. https://www.mapbox.com/ios-sdk/api/4.4.1/Protocols/MGLMapViewDelegate.html#/c:objc(pl)MGLMapViewDelegate(im)mapViewWillStartLoadingMap:

But I haven't seen any kind of flow chart.

> images are frowned upon by our documentation style guide

Why?

**Comment by jmkiley** [comment]
Images pose some accessibility issues: 

>  However, relying on images as the only medium for explaining a concept or workflow can make content difficult to follow for readers with visual impairments, readers who browse content without graphics, and non-native English speakers who use machine translation

https://hey.mapbox.com/documentation/style-guide/images-and-diagrams/

If we offer a diagram, we will also want to have text that explains the lifecycle.
