### ISSUE TITLE
Use new way to pull in and display access tokens

### ISSUE THREAD

**Issue by langsmith** [mapbox/android-docs#662]
Based on @colleenmcginnis 's comment at https://github.com/mapbox/android-docs/pull/650#discussion_r224147618

**Comment by langsmith** [comment]
I'd love to use this @colleenmcginnis . Is this functionality already being used somewhere so that I can see how it works? Should we plan for you to teach/show me during our next 1:1?

**Comment by langsmith** [comment]
@colleenmcginnis to set up a pr to show how to use this and then I will run with it

**Comment by langsmith** [comment]
Poke 👉 poke 👉  @colleenmcginnis

**Comment by colleenmcginnis** [comment]
This fell off my radar @langsmith. 😞 Maybe this is something @katydecorah could help with in the next couple weeks! 👸 

@katydecorah maybe we should make a shared `UserAccessToken` component in [dr-ui](https://github.com/mapbox/dr-ui) to use across all docs repos that have code snippets with access tokens.
