### ISSUE TITLE
Navigation - Update code samples to current version

### ISSUE THREAD

**Issue by voghDev** [mapbox/android-docs#665]
Hello,

in the [Navigation section](https://www.mapbox.com/android-docs/navigation/overview/#4-requesting-a-route) of the docs, there are some calls to `NavigationRoute.builder()` that now seem to receive a `Context` in `0.20.0`. For example this one:

    // From Mapbox to The White House
    Point origin = Point.fromLngLat(-77.03613, 38.90992);
    Point destination = Point.fromLngLat(-77.0365, 38.8977);

    NavigationRoute.builder()
          .accessToken(Mapbox.getAccessToken())
          .origin(origin)
          .destination(destination)
          .build()

Maybe the code sample could be updated to `NavigationRoute.builder(this)`  as the documentation usually refers to the scope of an Activity

There are 3 appearances of this call in total :-)

cc @Guardiola31337

**Comment by langsmith** [comment]
[This commit](https://github.com/mapbox/android-docs/commit/5abbb3c27f8f945d8d8e3f782a2c025b96223cbd#diff-c784640a02080e76b78ca9c122b1d804) resolved this ticket. Code snippets now have `NavigationRoute.builder(context)`
