### ISSUE TITLE
LocationComponent image/chrome is broken

### ISSUE THREAD

**Issue by langsmith** [mapbox/android-docs#684]
@colleenmcginnis , looks like and image and chrome are broken on https://www.mapbox.com/android-docs/maps/overview/location-component/

<img width="754" alt="screen shot 2018-10-19 at 9 23 39 am" src="https://user-images.githubusercontent.com/4394910/47192601-c473d400-d380-11e8-9d13-88f85d5a720f.png">

**Comment by colleenmcginnis** [comment]
@langsmith this page is looking ok for me... Are you still seeing this issue? What browser are you using? 

![screencapture-localhost-8080-android-docs-maps-overview-location-component-2018-10-23-17_31_50](https://user-images.githubusercontent.com/10479155/47398604-9b897100-d6e9-11e8-9388-0608f8643c45.png)

**Comment by colleenmcginnis** [comment]
Per chat with @langsmith it sounds like this issue is limited to Safari and Firefox. I am 🕵️‍♀️ now.

**Comment by langsmith** [comment]
Per chat with @colleenmcginnis , sounds like everything's working as expected. I'm currently in Beijing, so perhaps the issue is a weird connectivity/internet thing over here. Closing this issue for now. I will check the page once I'm back in America. I will re-open this issue if I'm still seeing problems on my end.

**Comment by langsmith** [comment]
@colleenmcginnis, I've reopened this because @LukasPaczos reported the same issue in #690

**Comment by langsmith** [comment]
I'm seeing the issue in Chrome now that I'm back in 🇺🇸

**Comment by langsmith** [comment]
Also seeing it in Firefox and Safari

**Comment by colleenmcginnis** [comment]
Weird. Not sure why I'm not seeing it. I'll just open a PR to remove the device frames for now.
