### ISSUE TITLE
Misaligned pictures for LocationComponent camera examples

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/android-docs#690]
![screenshot from 2018-10-24 16-53-27](https://user-images.githubusercontent.com/16925074/47439865-6e05fb80-d7ad-11e8-82e6-82471eeae88e.png)

/cc @langsmith

**Comment by langsmith** [comment]
Closing this as it's a duplicate of https://github.com/mapbox/android-docs/issues/684

Thanks @LukasPaczos
