### ISSUE TITLE
Add re-route to correct fragment location example page

### ISSUE THREAD

**Issue by langsmith** [mapbox/android-docs#747]
Was searching for something Mapbox-related on Google and clicked on the result which leads to https://www.mapbox.com/android-docs/plugins/examples/show-a-users-location-on-a-fragment, which.....404s 😭 

Need to add a re-route from https://www.mapbox.com/android-docs/plugins/examples/show-a-users-location-on-a-fragment/ to https://www.mapbox.com/android-docs/maps/examples/show-a-users-location-on-a-fragment/

**Comment by langsmith** [comment]
@katydecorah , @colleenmcginnis asked me to 👋 this to you

**Comment by langsmith** [comment]
🔪 🔪 🔪 🔪 🔪 🔪 🔪 🔪 🔪 🔪

**Comment by katydecorah** [comment]
🔪 404s my favorite 🔪

**Comment by katydecorah** [comment]
@langsmith I checked Google Analytics and the last time someone visited this URL was January 2019. I think Google's index took care of it, but please let me know if you continue to see it and I can set up a redirect.
