### ISSUE TITLE
`CodeLanguageToggle` breaks if not all `ToggleableCodeBlock`s have both Java & Kotlin examples

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/android-docs#752]
**Issue:**
The code toggle component breaks when some code snippets created using [`<ToggleableCodeBlock>`](https://github.com/mapbox/android-docs/blob/mb-pages/src/components/toggleable-code-block.js) contain [`<CodeLanguageToggle>`](https://github.com/mapbox/android-docs/blob/mb-pages/src/components/code-language-toggle.js) and others do not.

**To reproduce the issue:**
I encountered this problem when working on a page with multiple example sections created with `<ToggleableCodeBlock>`. Two sections had both Java and Kotlin snippets, while the other two only had Java snippets. 

When I ran the code locally, the page loaded correctly initially. However, it broke when when I clicked on the Kotlin toggle for one of the sections that had examples in both Java and Kotlin. Error message from dev tools was: `Uncaught TypeError: Cannot read property 'length' of undefined`

**Temporary fix:**
To resolve the issue, I added `kotlin={`n/a`}` to both of the example sections that did not have a Kotlin example. Not elegant, but it worked 😬 

I've since gotten Kotlin snippets for both sections, so it's not an active problem. But it may come up in future docs, so wanted to flag!

cc @mapbox/docs

**Comment by langsmith** [comment]
Closing this ticket.

Link to this ticket is added to this repo's README in https://github.com/mapbox/android-docs/pull/915
