### ISSUE TITLE
Broken link - mapbox.com/android-docs/

### ISSUE THREAD

**Issue by sherylseitz** [mapbox/android-docs#763]
**Type of issue**

Broken Link

**Priority**

Requires immediate attention.

**Description**

The link to the Matrix API on this page is dead.
https://www.mapbox.com/android-docs/java/overview/directions/

It points to this page:
https://www.mapbox.com/android-docs/mapbox-services/overview/directions-matrix/

Which returns a 404 error.

**Comment by jseppi** [comment]
Transferred this issue to `/android-docs` repo, cc @mapbox/docs
