### ISSUE TITLE
Blurb about CustomGeometrySource on data driven styling page misses the point

### ISSUE THREAD

**Issue by JesseCrocker** [mapbox/android-docs#789]
https://github.com/mapbox/android-docs/blob/5c19ef7eb19fe77ba83793fc7055e9674cb2ad72/src/pages/maps/overview/data-driven-styling.md#custom-geometry

It's not about rendering Geometries that can't be expressed as one of the GeoJSON types, IIRC it can only be used with those types. It's for adding data to the map that is dynamically generated, or needs to be loaded on demand.

**Comment by langsmith** [comment]
Thanks @JesseCrocker. Just addressed this in #807.
