### ISSUE TITLE
Update code snippet in Map Matching with NavigationView docs section

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/android-docs#795]
Code snippet in https://www.mapbox.com/android-docs/navigation/overview/map-matching/#map-matching-with-navigationview doesn't make too much sense - there's code after `allowRerouteFrom` is returning `false` 👀 

```java
@Override
public boolean allowRerouteFrom(Point offRoutePoint) {
  return false;
  
  // Fetch new route with MapboxMapMatching

  // Create new options with map matching response route
  NavigationViewOptions options = NavigationViewOptions.builder()
    .directionsRoute(mapMatchingDirectionsRoute)
    .build();
  navigationView.startNavigation(options);
}
```

**Comment by danesfeder** [comment]
`return false;` is correct here, just in the wrong spot - should come after we've call for the new route that we want instead of the internal `NavigationRoute`.  I opened #796 to fix the code snippets.
