### ISSUE TITLE
Add directions documentation

### ISSUE THREAD

**Issue by cammace** [mapbox/android-docs#8]

**Comment by ericrwolfe** [comment]
Noting that this is high priority to pair with the Navigation SDK documentation.

We should also look into link out to the relevant directions classes from the navigation docs

**Comment by langsmith** [comment]
I figure that [https://www.mapbox.com/android-docs/navigation/overview/](https://www.mapbox.com/android-docs/navigation/overview/ )  satisfies this ticket. Re-open if you disagree.

**Comment by ericrwolfe** [comment]
https://www.mapbox.com/android-docs/navigation/overview/ doesn't go into the details of using our MapboxDirections classes, and there are developers who might use Mapbox Directions without turn-by-turn navigation. 

We have documentation for DirectionsMatrix (https://www.mapbox.com/android-docs/mapbox-services/overview/directions-matrix/) within MAS, so it's confusing that there isn't a corresponding Directions section.

Reopening.

**Comment by langsmith** [comment]
Fyi, [I've started building out directions documentation here](https://github.com/mapbox/android-docs/blob/7fc58b08fb801d240890b45b60bbc4153f2179d0/pages/mapbox-services/overview/directions.md) and will continue working on it.

The bullet points in ☝️ are from @cammace 's original outlining of the directions content

**Comment by langsmith** [comment]
@danesfeder @Guardiola31337 @devotaaabel 

Do you all think that the content in https://www.mapbox.com/android-docs/navigation/overview/ satisfies (finally) closing this ticket? I'm not sure whether there are any major navigation topics that are missing from the Nav SDK area linked above.

**Comment by 1ec5** [comment]
I think the point of this ticket was to provide information about non-turn-by-turn use cases:

> there are developers who might use Mapbox Directions without turn-by-turn navigation

For example, we have [this documentation](https://www.mapbox.com/mapbox-navigation-ios/directions/) for MapboxDirections.swift, in addition to the navigation SDK documentation.

**Comment by langsmith** [comment]
🤦‍♂️ . Right. Second time I asked that in this ticket. It's been a long day.

**Comment by langsmith** [comment]
Closed via #210
