### ISSUE TITLE
Transfer www.mapbox.com/android-docs to docs.mapbox.com/android

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/android-docs#810]
@mapbox/frontend-platform and @mapbox/docs are working together to transfer this site to `docs.mapbox.com/android`.

Here are the steps in the process.

- [x] Launch the staging site at `docs.tilestream.net`.
- [x] QA the staging site .
- [x] Launch the production site at `docs.mapbox.com`.
- [x] 301 redirect from `www` to `docs`.
- [x] Adjust target repo list in docs-page-shell.
- [x] Change docs-page-shell so it points to the new URL.
- [ ] Change dotcom-page-shell so it points to the new URL.
- [ ] Delete `www` files and branches.

We're going to start on this today, and try to finish it today or tomorrow.

**Comment by davidtheclark** [comment]
The staging site is live at https://docs.tilestream.net/android.

@mapbox/docs can you please take a look? Things are looking good for me, with one caveat: there are some outdated links in the docs (e.g. to `/android-docs/map-sdk/` instead of `/android-docs/map`) that are currently relying on 301 redirects to work. These will not work on `docs.tilestream.net` (or the production equivalent) unless we either (a) make those link URLs absolute, so we can rely on redirects (which will work once we add new `docs`-targeting redirects), or (b) update those link URLs. Which would you prefer?

**Comment by katydecorah** [comment]
@davidtheclark I'm in favor of updating the link URLs, please let me know if you'd like help with this.

**Comment by davidtheclark** [comment]
@katydecorah I updated the outdated URLs I managed to find. If you find more, please list them out and I'll fix them 👍

**Comment by davidtheclark** [comment]
Production site is now live at https://docs.mapbox.com/android. Please let me know if you find any problems. Will implement the redirects later today.

**Comment by davidtheclark** [comment]
@katydecorah can you please finish the last steps?

- Switch the repo's main branch to publisher-production or publisher-staging.
- Change the base branch of open PRs.
- Delete the old `dev-pages` and `mb-pages` branches?

**Comment by katydecorah** [comment]
- [x] Switch the repo's main branch to publisher-production or publisher-staging.
- [x] Change the base branch of open PRs.
- [x] Delete the old `dev-pages` and `mb-pages` branches?

@mapbox/android as a heads up, the branches have changed on this repo:

* `mb-pages` -> `publisher-production`
* `dev-pages` -> `publisher-staging`

Please let me know if you have any questions!
