### ISSUE TITLE
Menu items flicker on page load of Navigation SDK for Android overview

### ISSUE THREAD

**Issue by malwoodsantoro** [mapbox/android-docs#814]
![android-sdk-docs](https://user-images.githubusercontent.com/19801577/51288710-468c8c80-19b2-11e9-8944-1dc193fd1a51.gif)

While browsing the docs, I noticed that `navigation` and `navigation-ui` menu items flicker on page load. Not a huge deal, but figured if anyone could fix it, it would be the Doc Queens. 

👑

**Comment by langsmith** [comment]
Is this still an issue?

**Comment by colleenmcginnis** [comment]
Should be fixed as of #872 -- if you continue to see this, please reopen!
