### ISSUE TITLE
Floater is floating over divider line

### ISSUE THREAD

**Issue by colleenmcginnis** [mapbox/android-docs#817]
`Floater` is floating on top of section divider. Example below is from https://docs.mapbox.com/android/plugins/overview/annotation/#options

![image](https://user-images.githubusercontent.com/10479155/51367446-7e253280-1a9f-11e9-8cff-bbdda2d208ae.png)

This component may also be a good candidate for dr-ui. 🎉  cc @katydecorah

**Comment by katydecorah** [comment]
@colleenmcginnis would you happen to know the goal of this styled block? I've seen a few of these around and not exactly sure what to call it yet or how I would know to use it. Could this styled block be a `Note` instead?

**Comment by katydecorah** [comment]
@colleenmcginnis I was thinking the same thing :) https://github.com/mapbox/dr-ui/issues/94
