### ISSUE TITLE
build script for updating javadoc with each release

### ISSUE THREAD

**Issue by cammace** [mapbox/android-docs#82]
The current process when generating javadoc after a new release occurs includes changing the `VERSION_NAME`, running the javadoc build, navigating to the output folder, renaming that folder to match the version name, and finally, moving that folder into the docs repo and commit/pushing the changes. 

A script can easily be created to simplify this progress across all our SDKs.

cc: @mapbox/android

**Comment by cammace** [comment]
I've written a python script that does everything but opens a PR for Javadoc. Once reviewed, I'll move it into all the Android repos.

https://github.com/mapbox/mapbox-navigation-android/pull/73

**Comment by zugaldia** [comment]
Removing my assignation, I won't have the bandwidth to focus on this short/medium-term. @cammace @langsmith could you pick this up?

**Comment by langsmith** [comment]
Resolved by @danswick 's great work in recent weeks: https://github.com/mapbox/android-docs/pulls?q=is%3Apr+is%3Aclosed+author%3Adanswick

My https://github.com/mapbox/android-docs/pull/1151 and https://github.com/mapbox/android-docs/pull/1143 are related.
