### ISSUE TITLE
Obtain MapboxMap object in Fragment

### ISSUE THREAD

**Issue by asterixorobelix** [mapbox/android-docs#821]
I have sucessfully instantiated Mapbox in my Activity and downloaded an offline region in the activity.

However, I am struggling to get access to the MapboxMap object in my fragment in order to use the moveCamera() method to the center of the offline region downloaded in the activity.

I have only been able to find examples which dont have any fragments. Can anyone point me in the right direction? My [Kotlin project is here](https://github.com/asterixorobelix/afrikaburn.kotlin/tree/offlineMap)

**Comment by asterixorobelix** [comment]
Thanks @tobrun 

I am familiar with implementing listeners via interfaces. 

I feel that my question is related to mapbox. So, are you saying that the getMapAsync method call is intended to be called in the activity where the Mapbox instance has been created?

**Comment by asterixorobelix** [comment]
@tobrun Maybe I am not being clear.

In my fragment - I am getting the MapView object (which is not null). I am then passing the MapView object to the host activity via a listener(interface). 

In the host activity - in the overriden listener(interface) method I am calling getMapAsync on the MapView object. However, the MapboxMap object which is obtained from this call is null. I can therefore not call the moveCamera method on the MapboxMap object. 

Does this sound to you like I can maybe too early in the lifecycle or something?

My Activity code is [here](https://github.com/asterixorobelix/afrikaburn.kotlin/blob/offlineMapV2/afrikaburn/app/src/main/java/io/github/asterixorobelix/afrikaburn/MainActivity.kt)

**Comment by tobrun** [comment]
@asterixorobelix 

This [example code](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/SupportMapFragmentActivity.java) should cover what you are trying to achieve. By using the `com.mapbox.mapboxsdk.maps.MapFragment` or `com.mapbox.mapboxsdk.maps.SupportMapFragment` state management is handled for you and callback interfaces are provided for MapboxMap and MapView. Hope this helps resolving your issues with setting up a MapView.

**Comment by asterixorobelix** [comment]
Thanks for the help @tobrun 

I gather that I was using moveCamera before the map was ready. I have changed by fragment to extend `com.mapbox.mapboxsdk.maps.SupportMapFragment` which gives me access to the onMapReady callback. 

However, the [Support map fragment example](https://docs.mapbox.com/android/maps/examples/support-map-fragment/) and [SupportMapFragmentActivity.java](https://github.com/mapbox/mapbox-gl-native/blob/master/platform/android/MapboxGLAndroidSDKTestApp/src/main/java/com/mapbox/mapboxsdk/testapp/activity/fragment/SupportMapFragmentActivity.java) seem to give contradictory advice.

Additionally, both make reference to SupportMapFragment.newInstance(options) - since my map is in a seperate fragment (inflated by the OS), I am uncertain how to achieve the same effect in my Activity.
