### ISSUE TITLE
Add CameraMode Options Example

### ISSUE THREAD

**Issue by riastrad** [mapbox/android-docs#854]
Since the `LocationComponent` was added to the Maps SDK, we've had the concept of different `CameraMode`s baked in, but we currently don't have any examples that showcase the 7 available options published on the website. 

I've opened up https://github.com/mapbox/mapbox-android-demo/issues/969 to get this added to the Demo App, and I'm opening up this ticket to track publishing the example to the website.

**Comment by langsmith** [comment]
https://github.com/mapbox/mapbox-android-demo/pull/1038 landed to `master` in the demo app and the example is now at https://docs.mapbox.com/android/maps/examples/location-component-camera-options/
