### ISSUE TITLE
Add Links to Older API Versions

### ISSUE THREAD

**Issue by riastrad** [mapbox/android-docs#868]
Reviving a thread started in #9. Currently all android-libraries' API links direct straight to the latest release's API documentation. However, developers are not always building with the latest version. This is problematic in instances where the SDKs increase by a semantic version and developers still need a convenient way to review the older API they're relying on. 

The good news is that all our older versions are still published and publically available. So the only level of effort required is to link them from our main docs pages (`https://docs.mapbox.com/android/{maps, navigation}/`).

Our iOS documentation uses a dropdown menu: 
<img width="525" alt="image" src="https://user-images.githubusercontent.com/16272584/53421688-13271f80-39ac-11e9-9615-9f29335399df.png">

I think this is the way to go, and hopefully it won't require too much strain. 

@mapbox/maps-android @mapbox/navigation-android FYI, this will likely modify your release process slightly, but hopefully it will just be a tweak to the step where you publish the generated documentation to the website and there won't be any additional steps added.

cc: @colleenmcginnis

**Comment by tobrun** [comment]
Love this!

**Comment by colleenmcginnis** [comment]
Addressed in #872 🎉
