### ISSUE TITLE
Add docs about new cache management

### ISSUE THREAD

**Issue by langsmith** [mapbox/android-docs#994]
https://github.com/mapbox/mapbox-gl-native/pull/14962 landed, which gives developers more flexibility around managing caching logic. Docs for this new caching logic need to be adjusted/added.

https://github.com/mapbox/mapbox-android-demo/issues/1015 is related

cc @mapbox/maps-android

**Comment by zugaldia** [comment]
cc: @jmkiley to coordinate the iOS flavor.
