### ISSUE TITLE
ScaleBar plugin does not require the geocoding API

### ISSUE THREAD

**Issue by tobrun** [mapbox/android-docs#998]
Capturing from @chloekraw that current docs on scalebar plugin seem to be informing users that geocoding is required while the only requirement is the maps sdk:

![Screenshot from 2019-07-10 09-39-35](https://user-images.githubusercontent.com/2151639/60950320-35845e80-a2f7-11e9-91df-fa9bab2f7574.png)

Link to docs [here](https://docs.mapbox.com/android/plugins/overview/scalebar/).

**Comment by chloekraw** [comment]
closed in https://github.com/mapbox/android-docs/pull/999 - thanks @langsmith!
